[package]
name = "noise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = { version = "0.8.2", features = ["images"] }
plotters = "0.3.5"
rand = "0.8.5"